export const styles = {
    container: {
        width: "100%",
        maxWidth: "1400px",
        margin: "0 auto",
        fontFamily: "Arial, sans-serif",
        backgroundColor: "#f4e4ca",
        padding: "20px",
        borderRadius: "8px",
    },
    header: {
        textAlign: "center",
        marginBottom: "20px",
    },
    title: {
        fontSize: "24px",
        fontWeight: "bold",
        color: "#333",
        marginBottom: "8px",
    },
    subtitle: {
        color: "#666",
        marginBottom: "20px",
    },
    calendar: {
        backgroundColor: "#fff",
        borderRadius: "4px",
        padding: "15px",
    },
    dayGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(5, 1fr)",
        gap: "1px",
        backgroundColor: "#ddd",
        border: "1px solid #ddd",
    },
    dayColumn: {
        backgroundColor: "#fff",
    },
    dayHeader: {
        textAlign: "center",
        padding: "10px",
        borderBottom: "1px solid #ddd",
        fontWeight: "bold",
    },
    periodHeaders: {
        display: "flex",
        justifyContent: "space-between",
        padding: "8px 10px",
        backgroundColor: "#f8f9fa",
        borderBottom: "1px solid #ddd",
        fontSize: "12px",
        color: "#666",
    },
    companySection: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
    },
    periodColumn: {
        backgroundColor: "#fff",
        padding: "10px",
        minHeight: "200px",
    },
    companyCard: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        padding: "8px",
        marginBottom: "8px",
        cursor: "pointer",
        transition: "all 0.2s ease",
        borderRadius: "4px",
    },
    companyInfo: {
        textAlign: "center",
        width: "100%",
    },
    exchange: {
        fontSize: "10px",
        color: "#888",
        backgroundColor: "#f5f5f5",
        padding: "1px 4px",
        borderRadius: "2px",
        display: "inline-block",
        marginBottom: "2px",
    },
    name: {
        fontSize: "12px",
        color: "#333",
        marginBottom: "2px",
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
        maxWidth: "120px",
    },
};
